runtime: nodejs20
entrypoint: npm start

env: standard
instance_class: F1

handlers:
  # API-Endpunkte
  - url: /api/.*
    script: auto

  # Statische Assets (JS, CSS, Bilder)
  - url: /(.*\.(js|css|png|jpg|svg|ico|json))
    static_files: public/\1
    upload: public/(.*\.(js|css|png|jpg|svg|ico|json))

  # SPA-Routing:
  - url: /.*
    static_files: public/index.html
    upload: public/index.html

env_variables:
  NODE_ENV: production
