runtime: nodejs20
entrypoint: npm start

env: standard
instance_class: F1

handlers:
  # API-Endpunkte gehen zu Express
  - url: /api/.*
    script: auto

  # Statische Frontend-Dateien
  - url: /(.*\.(js|css|png|jpg|svg|ico))
    static_files: public/\1
    upload: public/(.*\.(js|css|png|jpg|svg|ico))
    expiration: "1d"

  # Alle anderen Requests zu Express (SPA-Routing)
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: production
