runtime: nodejs20
entrypoint: npm start

env: standard
instance_class: F1

handlers:
  # API-Endpunkte
  - url: /api/.*
    script: auto

  # SPA-Routing für Frontend
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

env_variables:
  NODE_ENV: production
